version: '3'
services:
  qdrant:
    image: qdrant/qdrant:v1.7.3
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
  backend:
    build: ../backend
    ports:
      - "8000:8000"
    volumes:
      - ../scripts:/scripts
    depends_on:
      - qdrant
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
volumes:
  qdrant_data:
  ollama:
